const NODEL_FAILED = 'NODEL_FAILED';
const NOT_INCLUDED = 'NOT_INCLUDED';
const NOT_MATCHING = 'NOT_MATCHING'; 
const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED';
const WRONG_AUTH_TYPE = 'WRONG_AUTH_TYPE';
const OK = 'OK';
const GENESIS_MISMATCH = 'GENESIS_MISMATCH';
const DEST_MISMATCH = 'DEST_MISMATCH';
const PAYLOAD_MISMATCH = 'PAYLOAD_MISMATCH';
const INP_MISMATCH = 'INP_MISMATCH';

const DEFAULT_TEST_GATEWAY = 'https://gateway-test1.unicity.network:443';
const DEFAULT_LOCAL_GATEWAY = 'http://localhost:8847';

module.exports = { NODEL_FAILED, NOT_INCLUDED, NOT_MATCHING, NOT_AUTHENTICATED, OK, 
    GENESIS_MISMATCH, DEST_MISMATCH, PAYLOAD_MISMATCH, INP_MISMATCH, DEFAULT_LOCAL_GATEWAY, DEFAULT_TEST_GATEWAY }
